{% set version = "4.5.1" %}

package:
  name: pre-commit-split
  version: {{ version }}

source:
  url: https://github.com/pre-commit/pre-commit/archive/v{{ version }}.tar.gz
  sha256: ddfbb07ab492c30086af097c8346d8c4d0fc2fd3d5c19129e2df86c4db9e4aa9

build:
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel

outputs:
  - name: pre-commit
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    build:
      skip: true  # [py<310]
      entry_points:
        - pre-commit = pre_commit.main:main
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - cfgv >=2.0.0
        - identify >=1.0.0
        - nodeenv >=0.11.1
        - python
        - pyyaml >=5.1
        - virtualenv >=20.10.0
    test:
      imports:
        - pre_commit
        - pre_commit.all_languages
        - pre_commit.clientlib
        - pre_commit.color
        - pre_commit.commands
        - pre_commit.constants
        - pre_commit.envcontext
        - pre_commit.error_handler
        - pre_commit.errors
        - pre_commit.git
        - pre_commit.hook
        - pre_commit.lang_base
        - pre_commit.languages
        - pre_commit.logging_handler
        - pre_commit.main
        - pre_commit.meta_hooks
        - pre_commit.parse_shebang
        - pre_commit.prefix
        - pre_commit.repository
        - pre_commit.staged_files_only
        - pre_commit.store
        - pre_commit.util
        - pre_commit.xargs
        - pre_commit.yaml
        - pre_commit.yaml_rewrite
      requires:
        - pip
      commands:
        - pip check
        - where pre-commit  # [win]
        - pre-commit -V
        - pre-commit --help

  - name: pre_commit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pre-commit', max_pin="x.x.x") }}
    test:
      imports:
        - pre_commit

about:
  home: https://pre-commit.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for managing and maintaining multi-language pre-commit hooks.
  description: |
    pre-commit is a framework for managing and maintaining multi-language pre-commit hooks.
    It allows you to ensure that your code meets quality standards before you commit changes.
    pre-commit is language agnostic and plays nicely with other pre-commit tools.
  dev_url: https://github.com/pre-commit/pre-commit
  doc_url: https://pre-commit.com

extra:
  recipe-maintainers:
    - deadsnakes-issues-bot
    - nicoddemus
    - xmnlab
