{% set version = "3.4.0" %}

package:
  name: pre-commit-split
  version: {{ version }}

source:
  url: https://github.com/pre-commit/pre-commit/archive/v{{ version }}.tar.gz
  sha256: 65d63b57ddec920b09ffdf09536a480d6883eb5069eb295daab6d3fe151e34d3

build:
  number: 0
  skip: true  # [py<38]
  #entry_points:
  #  - pre-commit = pre_commit.main:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel

outputs:
  - name: pre-commit
    build:
      script: build_base.bat  # [win]
      script: build_base.sh  # [not win]
      activate_in_script: true
      entry_points:
        - pre-commit = pre_commit.main:main
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
        - virtualenv
      run:
        - cfgv >=2.0.0
        - identify >=1.0.0
        - nodeenv >=0.11.1
        - python
        - pyyaml >=5.1
        - virtualenv >=20.10.0
    test:
      imports:
        - pre_commit
        - pre_commit.commands
        - pre_commit.languages
        - pre_commit.meta_hooks
        - pre_commit.resources
      requires:
        - pip
      commands:
        - pip check
        - pre-commit -V
        - pre-commit --help

  # - name: pre_commit
  #   build:
  #     noarch: generic
  #   requirements:
  #     run:
  #       - {{ pin_subpackage('pre-commit', max_pin="x.x.x") }}
  #   test:
  #     imports:
  #       - pre_commit

about:
  home: https://pre-commit.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for managing and maintaining multi-language pre-commit hooks.
  description: |
    pre-commit is a framework for managing and maintaining multi-language pre-commit hooks.
    It allows you to ensure that your code meets quality standards before you commit changes.
    pre-commit is language agnostic and plays nicely with other pre-commit tools.
  dev_url: https://github.com/pre-commit/pre-commit
  doc_url: https://pre-commit.com/

extra:
  recipe-maintainers:
    - deadsnakes-issues-bot
    - nicoddemus
    - xmnlab
