travis:
  secure:
    BINSTAR_TOKEN: e2PwOBQqyFtFNHoRvVh5t7oxSt6FKlKymLktyvrtwOA4GDmFHIY9CJJ1JeDzS8Q7RBvMsWF7wz4AXu4kJOBDW907AS93oXVKFgdZ+jslhh3seXGWAO22CPfDjZF9G+JI7eEHWWX8dVIZrdCkUv0udZEG9qOWNY6OI3XezDrTWL1L2qCOIhS8NAmEhi9gJb2VpsUsqB38UWtyaMKt8dyINy5shBZWk6NEz0+sGMlRN9s+vGlSMxRPCNE05mWqKX7f4RVFqtSmuBWhIfAjXc6pCZm7NOqXwuUb+bdawbsc2SIdJuTeFJke01Fg7NaokC+aqG2JAd3HhgknshryPFa990FlMY7/it7vxBM6AnlWuVCC9vyP2M35U5HvVy409ctYa+afF2gUUCgrSSFHZ6+oj5sYA0MnH5i8LLdfu4a5gpqR/Vv+mNpt6w+q0WX1xisBTW9ssecsVJRTpxVZ4V9di0JOqN3OuU0VLP+dZben7Bp3lg7kM8AD9e518wqN7ZPT9bB6ammx6h/kjy0Qkk2kPKuQcxm3t0iLtyNFgfzdmgBzIDHlHVKMIK4JtY10FDYKz97yujrJCZkx1xUp6+KfLvJGkR4tYUFdzo2mzowzkUK2d+Gazgy4jUqt0tdCwUYh6BDC5a56QisJiisLgHHekjXrAt2va++h+CuNvu2NqnA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
